In [6]:
import pandas as pd

df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=["A", "B", "C"] , index=["x", "y", "z"])

In [ ]:
df

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [ ]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [ ]:
df

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [ ]:
df['A'].unique()

array([1, 4, 7])

In [11]:
coffee = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv')

In [12]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [13]:
coffee.tail()

         Day Coffee Type  Units Sold
9     Friday       Latte          35
10  Saturday    Espresso          45
11  Saturday       Latte          35
12    Sunday    Espresso          45
13    Sunday       Latte          35

In [14]:
coffee.loc[0:3, ["Coffee Type"]]

  Coffee Type
0    Espresso
1       Latte
2    Espresso
3       Latte

In [15]:
coffee.sort_values("Units Sold", ascending=False)

          Day Coffee Type  Units Sold
10   Saturday    Espresso          45
8      Friday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
11   Saturday       Latte          35
13     Sunday       Latte          35
9      Friday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          15

In [16]:
bios = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/bios.csv')

In [17]:
bios[bios['height_cm'] > 215][['name', 'height_cm']]

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

In [18]:
bios.loc[bios['height_cm'] > 215, ['name', 'height_cm']]

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

In [19]:
bios[(bios['height_cm'] > 215) & (bios['born_country'] == 'USA')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

In [20]:
bios[bios['name'].str.contains("Tony|Smith", case=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
46,47,Gladys Eastlake-Smith,1883-08-14,Lewisham,England,GBR,Great Britain,NaN,NaN,1941-09-18
68,69,Sam Smith,1971-11-27,Epping,England,GBR,Great Britain,175.0,62.0,NaN
659,662,Roger Smith,1964-01-20,Freeport,City of Freeport,BAH,The Bahamas,185.0,79.0,NaN
1017,1021,Tony Mmoh,1958-06-14,Enugu,Enugu,NGR,Nigeria,177.0,81.0,NaN
1031,1038,Trygve Smith,1880-09-20,Oslo,Oslo,NOR,Norway,NaN,NaN,1948-11-10
...,...,...,...,...,...,...,...,...,...,...
143586,147239,Austen Smith,2001-07-23,NaN,NaN,NaN,United States,170.0,NaN,NaN
143591,147244,Alana Smith,2000-10-20,Mesa,Arizona,USA,United States,NaN,NaN,NaN
143629,147282,Regan Smith,2002-02-09,Lakeville,Minnesota,USA,United States,NaN,NaN,NaN
143816,147472,Kieran Smith,2000-05-20,NaN,NaN,NaN,United States,NaN,NaN,NaN
145421,149144,Nathan Smith,1998-10-19,Tampa,Florida,USA,United States,NaN,NaN,NaN

In [21]:
bios[bios['born_country'].isin(["USA","GBR","FRA"]) & bios['name'].str.contains("Tony")]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
3519,3531,Tony Willis,1960-06-17,Liverpool,England,GBR,Great Britain,170.0,64.0,NaN
3521,3533,Tony Wilson,1961-04-15,Wolverhampton,England,GBR,Great Britain,180.0,81.0,NaN
11085,11144,Tony Ralphs,1943-12-11,Los Angeles,California,USA,United States,183.0,66.0,NaN
11650,11711,Tony Cameron,1941-03-21,Ashford,England,GBR,Ireland,175.0,61.0,NaN
14098,14191,Tony Doyle,1958-05-19,Ashford,England,GBR,Great Britain,185.0,79.0,2023-04-30
...,...,...,...,...,...,...,...,...,...,...
118077,119637,Tony Ramoin,1988-12-23,Cannes,Alpes-Maritimes,FRA,France,183.0,74.0,NaN
122535,124635,Tony Yoka,1992-04-28,Paris XVIIIe,Paris,FRA,France,200.0,105.0,NaN
122879,125021,Tony Gallopin,1988-05-24,Dourdan,Essonne,FRA,France,179.0,72.0,NaN
124687,127009,Tony McQuay,1990-04-16,West Palm Beach,Florida,USA,United States,181.0,72.0,NaN
131090,133854,Jean-Paul Tony Helissey,1990-03-28,Pointe-à-Pitre,Guadeloupe,FRA,France,177.0,77.0,NaN

In [22]:
bios.query('born_country == "RUS" and born_region == "Moskva"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
158,159,Robert Spies,1891-02-17,Moskva (Moscow),Moskva,RUS,Germany,NaN,NaN,1982-10-22
2522,2534,Marina Yakusheva,1974-06-19,Moskva (Moscow),Moskva,RUS,Russian Federation,170.0,55.0,NaN
2523,2535,Anna Kournikova,1981-06-07,Moskva (Moscow),Moskva,RUS,Russian Federation,173.0,56.0,NaN
2525,2537,Yelena Makarova,1973-02-01,Moskva (Moscow),Moskva,RUS,Russian Federation,179.0,65.0,NaN
2526,2538,Irina Palina,1970-01-15,Moskva (Moscow),Moskva,RUS,Russian Federation Unified Team,162.0,60.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145334,149056,Anastasiya Shabotova,2006-01-17,Moskva (Moscow),Moskva,RUS,Ukraine,NaN,NaN,NaN
145450,149174,Anna Shcherbakova,2004-03-28,Moskva (Moscow),Moskva,RUS,ROC,NaN,NaN,NaN
145465,149192,Stanislav Galiyev,1992-01-17,Moskva (Moscow),Moskva,RUS,ROC,188.0,82.0,NaN
145487,149214,Yekaterina Kosova,1996-04-25,Moskva (Moscow),Moskva,RUS,ROC,NaN,NaN,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN

In [23]:
coffee['price'] = 4.99

In [24]:
import numpy as np
coffee['new_price'] = np.where(coffee['Coffee Type']=='Espresso', 3.99, 5.99)

In [25]:
coffee

          Day Coffee Type  Units Sold  price  new_price
0      Monday    Espresso          25   4.99       3.99
1      Monday       Latte          15   4.99       5.99
2     Tuesday    Espresso          30   4.99       3.99
3     Tuesday       Latte          20   4.99       5.99
4   Wednesday    Espresso          35   4.99       3.99
5   Wednesday       Latte          25   4.99       5.99
6    Thursday    Espresso          40   4.99       3.99
7    Thursday       Latte          30   4.99       5.99
8      Friday    Espresso          45   4.99       3.99
9      Friday       Latte          35   4.99       5.99
10   Saturday    Espresso          45   4.99       3.99
11   Saturday       Latte          35   4.99       5.99
12     Sunday    Espresso          45   4.99       3.99
13     Sunday       Latte          35   4.99       5.99

In [26]:
#coffee.drop(columns=['price'], inplace =True)
coffee

          Day Coffee Type  Units Sold  price  new_price
0      Monday    Espresso          25   4.99       3.99
1      Monday       Latte          15   4.99       5.99
2     Tuesday    Espresso          30   4.99       3.99
3     Tuesday       Latte          20   4.99       5.99
4   Wednesday    Espresso          35   4.99       3.99
5   Wednesday       Latte          25   4.99       5.99
6    Thursday    Espresso          40   4.99       3.99
7    Thursday       Latte          30   4.99       5.99
8      Friday    Espresso          45   4.99       3.99
9      Friday       Latte          35   4.99       5.99
10   Saturday    Espresso          45   4.99       3.99
11   Saturday       Latte          35   4.99       5.99
12     Sunday    Espresso          45   4.99       3.99
13     Sunday       Latte          35   4.99       5.99

In [27]:
coffee = coffee[['Day', 'Coffee Type','Units Sold','new_price']]

In [28]:
coffee.head()

         Day Coffee Type  Units Sold  new_price
0     Monday    Espresso          25       3.99
1     Monday       Latte          15       5.99
2    Tuesday    Espresso          30       3.99
3    Tuesday       Latte          20       5.99
4  Wednesday    Espresso          35       3.99

In [29]:
coffee['revenue'] = coffee['Units Sold'] * coffee['new_price']

In [30]:
coffee.head(10)

         Day Coffee Type  Units Sold  new_price  revenue
0     Monday    Espresso          25       3.99    99.75
1     Monday       Latte          15       5.99    89.85
2    Tuesday    Espresso          30       3.99   119.70
3    Tuesday       Latte          20       5.99   119.80
4  Wednesday    Espresso          35       3.99   139.65
5  Wednesday       Latte          25       5.99   149.75
6   Thursday    Espresso          40       3.99   159.60
7   Thursday       Latte          30       5.99   179.70
8     Friday    Espresso          45       3.99   179.55
9     Friday       Latte          35       5.99   209.65

In [31]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [32]:
bios_new = bios.copy()

In [33]:
bios_new['first_name'] = bios_new['name'].str.split(' ').str[0]

In [34]:
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert
...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill

In [35]:
bios_new.query('first_name == "Keith"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN,Keith
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31,Keith
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN,Keith
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09,Keith
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22,Keith
...,...,...,...,...,...,...,...,...,...,...,...
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN,Keith
102227,103168,Keith Beavers,1983-02-09,London,Ontario,CAN,Canada,185.0,75.0,NaN,Keith
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15,Keith
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN,Keith
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN,Keith

In [36]:
bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date'], errors='coerce')

In [37]:
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17
...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina,2002-01-30
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya,1999-09-20
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya,1998-05-08
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André,1899-05-19
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill,1913-07-15

Convert born_date from int format to datetime format so we can male a year column

In [38]:
bios_new['born_year'] = bios_new['born_datetime'].dt.year

bios_new[['name', 'born_year']]

                         name  born_year
0       Jean-François Blanchy     1886.0
1              Arnaud Boetsch     1969.0
2                Jean Borotra     1898.0
3             Jacques Brugnon     1895.0
4                Albert Canet     1878.0
...                       ...        ...
145495      Polina Luchnikova     2002.0
145496    Valeriya Merkusheva     1999.0
145497        Yuliya Smirnova     1998.0
145498         André Foussard     1899.0
145499          Bill Phillips     1913.0

[145500 rows x 2 columns]

In [39]:
bios_new.to_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/bios.csv', index=False)

In [40]:
bios['height_category'] = bios['height_cm'].apply(lambda x: 'Short' if x < 165 else ('Average' if x < 185 else 'Tall' ))

In [41]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall

In [42]:
def categorize_athlete(row):
    if row['height_cm'] < 175 and row['weight_kg'] < 70:
        return 'Lightweight'
    elif row['height_cm'] < 185 or row['weight_kg'] <= 80:
        return 'Middleweight'
    
    else:
        return 'Heavyweight'
    
bios['Category'] = bios.apply(categorize_athlete, axis = 1)

In [43]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,Middleweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,Middleweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,Lightweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavyweight

In [44]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,Middleweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,Middleweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,Lightweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavyweight

In [45]:
nocs = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/noc_regions.csv')

In [46]:
nocs.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [47]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,Middleweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,Middleweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,Lightweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavyweight

NOW WE WANNA MERGE DATA !!!!!!!!

In [48]:
bios_new = pd.merge(bios, nocs, left_on='born_country', right_on='NOC', how='left')

In [49]:
bios_new.rename(columns={'region': 'born_country_full'}, inplace = True)

In [50]:
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,height_category,Category,NOC_y,born_country_full,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,Middleweight,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,Middleweight,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,Lightweight,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavyweight,GBR,UK,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Average,Lightweight,RUS,Russia,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Average,Lightweight,RUS,Russia,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Short,Lightweight,RUS,Russia,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,Average,Middleweight,FRA,France,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Tall,Heavyweight,AUS,Australia,NaN

In [51]:
usa = bios[bios['born_country']=='USA'].copy()
gbr = bios[bios['born_country']=='GBR'].copy()

In [52]:
usa.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN,Average,Middleweight
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN,Average,Lightweight
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN,Short,Lightweight
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20,Tall,Heavyweight
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN,Average,Lightweight

Если мы хотим сделать новый датафрэм, то это будет

In [53]:
new_df = pd.concat([usa,gbr])

In [54]:
new_df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN,Average,Middleweight
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN,Average,Lightweight
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN,Short,Lightweight
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20,Tall,Heavyweight
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN,Average,Lightweight

In [55]:
results = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/results.csv')

In [56]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [57]:
combined_df = pd.merge(results, bios, on='athlete_id', how='left')

In [58]:
combined_df.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,...,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight

Handling NULL values

In [59]:
coffee.loc[[4,5], 'Units Sold'] = np.nan

In [60]:
coffee.loc[[0,1], 'Units Sold'] = 15

In [61]:
coffee.isna().sum()

Day            0
Coffee Type    0
Units Sold     2
new_price      0
revenue        0
dtype: int64

Check for missing info

In [62]:
coffee.fillna(coffee['Units Sold'].mean())

          Day Coffee Type  Units Sold  new_price  revenue
0      Monday    Espresso        15.0       3.99    99.75
1      Monday       Latte        15.0       5.99    89.85
2     Tuesday    Espresso        30.0       3.99   119.70
3     Tuesday       Latte        20.0       5.99   119.80
4   Wednesday    Espresso        32.5       3.99   139.65
5   Wednesday       Latte        32.5       5.99   149.75
6    Thursday    Espresso        40.0       3.99   159.60
7    Thursday       Latte        30.0       5.99   179.70
8      Friday    Espresso        45.0       3.99   179.55
9      Friday       Latte        35.0       5.99   209.65
10   Saturday    Espresso        45.0       3.99   179.55
11   Saturday       Latte        35.0       5.99   209.65
12     Sunday    Espresso        45.0       3.99   179.55
13     Sunday       Latte        35.0       5.99   209.65

In [63]:
coffee

          Day Coffee Type  Units Sold  new_price  revenue
0      Monday    Espresso        15.0       3.99    99.75
1      Monday       Latte        15.0       5.99    89.85
2     Tuesday    Espresso        30.0       3.99   119.70
3     Tuesday       Latte        20.0       5.99   119.80
4   Wednesday    Espresso         NaN       3.99   139.65
5   Wednesday       Latte         NaN       5.99   149.75
6    Thursday    Espresso        40.0       3.99   159.60
7    Thursday       Latte        30.0       5.99   179.70
8      Friday    Espresso        45.0       3.99   179.55
9      Friday       Latte        35.0       5.99   209.65
10   Saturday    Espresso        45.0       3.99   179.55
11   Saturday       Latte        35.0       5.99   209.65
12     Sunday    Espresso        45.0       3.99   179.55
13     Sunday       Latte        35.0       5.99   209.65

In [64]:
coffee['Units Sold'] = coffee['Units Sold'].interpolate()

In [65]:
coffee

          Day Coffee Type  Units Sold  new_price  revenue
0      Monday    Espresso   15.000000       3.99    99.75
1      Monday       Latte   15.000000       5.99    89.85
2     Tuesday    Espresso   30.000000       3.99   119.70
3     Tuesday       Latte   20.000000       5.99   119.80
4   Wednesday    Espresso   26.666667       3.99   139.65
5   Wednesday       Latte   33.333333       5.99   149.75
6    Thursday    Espresso   40.000000       3.99   159.60
7    Thursday       Latte   30.000000       5.99   179.70
8      Friday    Espresso   45.000000       3.99   179.55
9      Friday       Latte   35.000000       5.99   209.65
10   Saturday    Espresso   45.000000       3.99   179.55
11   Saturday       Latte   35.000000       5.99   209.65
12     Sunday    Espresso   45.000000       3.99   179.55
13     Sunday       Latte   35.000000       5.99   209.65

Maybe you want to throw out out any data with NaN

In [66]:
coffee.dropna(subset=['Units Sold']) #if you want to save it memory put inplace=True(coffee = coffee.dropna(subset=['Units Sold']), inplace = True)

          Day Coffee Type  Units Sold  new_price  revenue
0      Monday    Espresso   15.000000       3.99    99.75
1      Monday       Latte   15.000000       5.99    89.85
2     Tuesday    Espresso   30.000000       3.99   119.70
3     Tuesday       Latte   20.000000       5.99   119.80
4   Wednesday    Espresso   26.666667       3.99   139.65
5   Wednesday       Latte   33.333333       5.99   149.75
6    Thursday    Espresso   40.000000       3.99   159.60
7    Thursday       Latte   30.000000       5.99   179.70
8      Friday    Espresso   45.000000       3.99   179.55
9      Friday       Latte   35.000000       5.99   209.65
10   Saturday    Espresso   45.000000       3.99   179.55
11   Saturday       Latte   35.000000       5.99   209.65
12     Sunday    Espresso   45.000000       3.99   179.55
13     Sunday       Latte   35.000000       5.99   209.65

In [67]:
coffee[coffee['Units Sold'].isna()]

Empty DataFrame
Columns: [Day, Coffee Type, Units Sold, new_price, revenue]
Index: []

In [68]:
coffee[coffee['Units Sold'].notna()]

          Day Coffee Type  Units Sold  new_price  revenue
0      Monday    Espresso   15.000000       3.99    99.75
1      Monday       Latte   15.000000       5.99    89.85
2     Tuesday    Espresso   30.000000       3.99   119.70
3     Tuesday       Latte   20.000000       5.99   119.80
4   Wednesday    Espresso   26.666667       3.99   139.65
5   Wednesday       Latte   33.333333       5.99   149.75
6    Thursday    Espresso   40.000000       3.99   159.60
7    Thursday       Latte   30.000000       5.99   179.70
8      Friday    Espresso   45.000000       3.99   179.55
9      Friday       Latte   35.000000       5.99   209.65
10   Saturday    Espresso   45.000000       3.99   179.55
11   Saturday       Latte   35.000000       5.99   209.65
12     Sunday    Espresso   45.000000       3.99   179.55
13     Sunday       Latte   35.000000       5.99   209.65

ABOVE THERE JUST SOME FILTERING CONDITIONS

AGGREGATING DATA
YESSSS

In [69]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,Middleweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,Middleweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,Lightweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavyweight

In [70]:
bios['born_city'].value_counts()

born_city
Budapest            1378
Moskva (Moscow)      883
Oslo                 708
Stockholm            629
Praha (Prague)       600
                    ...
Tsivilsk               1
Roth                   1
Romoos                 1
Dva Polya Artash       1
Dulwich Hill           1
Name: count, Length: 22368, dtype: int64

In [71]:
bios[bios['born_country'] == 'USA']['born_region'].value_counts()

born_region
California              1634
New York                 990
Illinois                 585
Pennsylvania             530
Massachusetts            530
New Jersey               381
Texas                    368
Minnesota                365
Ohio                     328
Michigan                 319
Washington               240
Florida                  235
Wisconsin                209
Colorado                 207
Connecticut              156
Indiana                  150
Oregon                   132
Georgia                  129
Virginia                 121
Maryland                 117
District of Columbia     107
Iowa                     102
Hawaiʻi                   95
Kansas                    94
Oklahoma                  93
Louisiana                 92
Utah                      91
Missouri                  91
North Carolina            86
Arizona                   83
New Hampshire             83
Vermont                   68
Mississippi               66
Alabama                   64
Tennessee                 62
Kentucky                  62
Nebraska                  60
Rhode Island              56
Montana                   55
Maine                     50
South Carolina            50
Alaska                    45
Arkansas                  42
Idaho                     41
New Mexico                38
Nevada                    36
South Dakota              27
West Virginia             24
Delaware                  22
North Dakota              16
Wyoming                   14
Name: count, dtype: int64

In [72]:
bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,Middleweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,Middleweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,Lightweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavyweight
...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Average,Lightweight
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Average,Lightweight
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Short,Lightweight
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,Average,Middleweight
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Tall,Heavyweight

In [73]:
coffee

          Day Coffee Type  Units Sold  new_price  revenue
0      Monday    Espresso   15.000000       3.99    99.75
1      Monday       Latte   15.000000       5.99    89.85
2     Tuesday    Espresso   30.000000       3.99   119.70
3     Tuesday       Latte   20.000000       5.99   119.80
4   Wednesday    Espresso   26.666667       3.99   139.65
5   Wednesday       Latte   33.333333       5.99   149.75
6    Thursday    Espresso   40.000000       3.99   159.60
7    Thursday       Latte   30.000000       5.99   179.70
8      Friday    Espresso   45.000000       3.99   179.55
9      Friday       Latte   35.000000       5.99   209.65
10   Saturday    Espresso   45.000000       3.99   179.55
11   Saturday       Latte   35.000000       5.99   209.65
12     Sunday    Espresso   45.000000       3.99   179.55
13     Sunday       Latte   35.000000       5.99   209.65

In [74]:
coffee.groupby(['Coffee Type']) ['Units Sold'].sum()

Coffee Type
Espresso    246.666667
Latte       203.333333
Name: Units Sold, dtype: float64

In [75]:
coffee.groupby(['Coffee Type', 'Day']).agg({'Units Sold': 'sum', 'new_price': 'mean'})

                       Units Sold  new_price
Coffee Type Day
Espresso    Friday      45.000000       3.99
            Monday      15.000000       3.99
            Saturday    45.000000       3.99
            Sunday      45.000000       3.99
            Thursday    40.000000       3.99
            Tuesday     30.000000       3.99
            Wednesday   26.666667       3.99
Latte       Friday      35.000000       5.99
            Monday      15.000000       5.99
            Saturday    35.000000       5.99
            Sunday      35.000000       5.99
            Thursday    30.000000       5.99
            Tuesday     20.000000       5.99
            Wednesday   33.333333       5.99

In [76]:
pivot = coffee.pivot(columns='Coffee Type', index = 'Day', values='revenue' )

In [77]:
pivot.sum()

Coffee Type
Espresso    1057.35
Latte       1168.05
dtype: float64

In [78]:
pivot.sum(axis=1) #Rev per day

Day
Friday       389.2
Monday       189.6
Saturday     389.2
Sunday       389.2
Thursday     339.3
Tuesday      239.5
Wednesday    289.4
dtype: float64

In [79]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,Middleweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,Middleweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,Lightweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavyweight

In [80]:
bios['born_date'] = pd.to_datetime(bios['born_date'])

bios.groupby(bios['born_date'].dt.year)['name'].count().reset_index().sort_values('name', ascending=False)

     born_date  name
139     1972.0  2231
152     1985.0  2227
140     1973.0  2216
138     1971.0  2205
137     1970.0  2174
..         ...   ...
4       1837.0     1
2       1833.0     1
6       1839.0     1
12      1845.0     1
176     2009.0     1

[177 rows x 2 columns]

SOME ADVANCED FUNCTIONALITY

In [81]:
coffee['yesterday_revenue'] = coffee['revenue'].shift(2)

In [82]:
coffee['pct_revenue'] = coffee['revenue'] / coffee['yesterday_revenue'] * 100

In [83]:
coffee

,Day,Coffee Type,Units Sold,new_price,revenue,yesterday_revenue,pct_revenue
0,Monday,Espresso,15.000000,3.99,99.75,NaN,NaN
1,Monday,Latte,15.000000,5.99,89.85,NaN,NaN
2,Tuesday,Espresso,30.000000,3.99,119.70,99.75,120.000000
3,Tuesday,Latte,20.000000,5.99,119.80,89.85,133.333333
4,Wednesday,Espresso,26.666667,3.99,139.65,119.70,116.666667
5,Wednesday,Latte,33.333333,5.99,149.75,119.80,125.000000
6,Thursday,Espresso,40.000000,3.99,159.60,139.65,114.285714
7,Thursday,Latte,30.000000,5.99,179.70,149.75,120.000000
8,Friday,Espresso,45.000000,3.99,179.55,159.60,112.500000
9,Friday,Latte,35.000000,5.99,209.65,179.70,116.666667
10,Saturday,Espresso,45.000000,3.99,179.55,179.55,100.000000
11,Saturday,Latte,35.000000,5.99,209.65,209.65,100.000000
12,Sunday,Espresso,45.000000,3.99,179.55,179.55,100.000000
13,Sunday,Latte,35.000000,5.99,209.65,209.65,100.000000

In [84]:
bios['height_rank'] = bios['height_cm'].rank()

In [86]:
bios.sort_values(['height_rank'], ascending=False)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category,height_rank
89070,89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN,Tall,Heavyweight,106651.0
6978,7013,Arvydas Sabonis,1964-12-19,Kaunas,Kaunas,LTU,Lithuania Soviet Union,223.0,122.0,NaN,Tall,Heavyweight,106649.5
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN,Tall,Heavyweight,106649.5
89075,89787,Roberto Dueñas,1975-11-01,Madrid,Madrid,ESP,Spain,221.0,137.0,NaN,Tall,Heavyweight,106647.0
120266,122147,Zhang Zhaoxu,1987-11-18,Binzhou,Shandong,CHN,People's Republic of China,221.0,110.0,NaN,Tall,Heavyweight,106647.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145490,149217,Sin Ye-Chan,1995-06-13,NaN,NaN,NaN,Republic of Korea,NaN,NaN,NaN,Tall,Heavyweight,NaN
145491,149218,Matthew Wepke,1989-12-05,NaN,NaN,NaN,Jamaica,NaN,NaN,NaN,Tall,Heavyweight,NaN
145492,149219,Carlos García-Ordóñez,1927-04-24,La Habana (Havana),Ciudad de La Habana,CUB,Cuba,NaN,NaN,2019-11-24,Tall,Heavyweight,NaN
145493,149220,Landysh Falyakhova,1998-08-31,Dva Polya Artash,Respublika Tatarstan,RUS,ROC,NaN,NaN,NaN,Tall,Heavyweight,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Tall,Heavyweight,NaN

In [87]:
coffee.head()

,Day,Coffee Type,Units Sold,new_price,revenue,yesterday_revenue,pct_revenue
0,Monday,Espresso,15.000000,3.99,99.75,NaN,NaN
1,Monday,Latte,15.000000,5.99,89.85,NaN,NaN
2,Tuesday,Espresso,30.000000,3.99,119.70,99.75,120.000000
3,Tuesday,Latte,20.000000,5.99,119.80,89.85,133.333333
4,Wednesday,Espresso,26.666667,3.99,139.65,119.70,116.666667

In [89]:
coffee['cumulative_revenue'] = coffee['revenue'].cumsum()

In [91]:
coffee

,Day,Coffee Type,Units Sold,new_price,revenue,yesterday_revenue,pct_revenue,cumulative_revenue
0,Monday,Espresso,15.000000,3.99,99.75,NaN,NaN,99.75
1,Monday,Latte,15.000000,5.99,89.85,NaN,NaN,189.60
2,Tuesday,Espresso,30.000000,3.99,119.70,99.75,120.000000,309.30
3,Tuesday,Latte,20.000000,5.99,119.80,89.85,133.333333,429.10
4,Wednesday,Espresso,26.666667,3.99,139.65,119.70,116.666667,568.75
5,Wednesday,Latte,33.333333,5.99,149.75,119.80,125.000000,718.50
6,Thursday,Espresso,40.000000,3.99,159.60,139.65,114.285714,878.10
7,Thursday,Latte,30.000000,5.99,179.70,149.75,120.000000,1057.80
8,Friday,Espresso,45.000000,3.99,179.55,159.60,112.500000,1237.35
9,Friday,Latte,35.000000,5.99,209.65,179.70,116.666667,1447.00
10,Saturday,Espresso,45.000000,3.99,179.55,179.55,100.000000,1626.55
11,Saturday,Latte,35.000000,5.99,209.65,209.65,100.000000,1836.20
12,Sunday,Espresso,45.000000,3.99,179.55,179.55,100.000000,2015.75
13,Sunday,Latte,35.000000,5.99,209.65,209.65,100.000000,2225.40

In [96]:
latte = coffee[coffee['Coffee Type'] == "Latte"].copy()
latte ['3day'] = latte['Units Sold'].rolling(3).sum()

In [97]:
latte

,Day,Coffee Type,Units Sold,new_price,revenue,yesterday_revenue,pct_revenue,cumulative_revenue,3day
1,Monday,Latte,15.000000,5.99,89.85,NaN,NaN,189.6,NaN
3,Tuesday,Latte,20.000000,5.99,119.80,89.85,133.333333,429.1,NaN
5,Wednesday,Latte,33.333333,5.99,149.75,119.80,125.000000,718.5,68.333333
7,Thursday,Latte,30.000000,5.99,179.70,149.75,120.000000,1057.8,83.333333
9,Friday,Latte,35.000000,5.99,209.65,179.70,116.666667,1447.0,98.333333
11,Saturday,Latte,35.000000,5.99,209.65,209.65,100.000000,1836.2,100.000000
13,Sunday,Latte,35.000000,5.99,209.65,209.65,100.000000,2225.4,105.000000